version: '3'  # optional since v1.27.0
services:
  jenkins:
    image :  jenkins/jenkins
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
    - /home/pradip/jenkins:/var/jenkins_home jenkins
    restart: unless-stopped